package com.tabber.tabby.constants;

import java.util.Map;

import static java.util.Map.entry;

public interface UniversityListConstants {
    Map<Integer, String> universityList = Map.ofEntries(
            entry(0,"Acharya Nagarjuna University, Nagarjuna Nagar-522510, Dt. Guntur, Andhra Pradesh. (State University)"),
            entry(1,"Acharya N.G. Ranga Agricultural University, Lam, Guntur- 522 034, Telangana. (State University)"),
            entry(2,"Adikavi Nannaya University, 25-7-9/1, Jayakrishnapuram, Rajahmundry – 533 105, East Godavari District, Andhra Pradesh. (State University)"),
            entry(3,"Andhra University, Waltair, Visakhapatnam-530 003, Andhra Pradesh. (State University)"),
            entry(4,"Bhartiya Engineering Acience and Technology Innovation University, Gownivaripalli, Gorantla Mandal, Anantapur Andhra Pradesh. (Privte University)"),
            entry(5,"Central Tribal University of Andhra Pradesh, Kondakarakam, Vizianagaram, Andhra Pradesh – 535003. (Central University)"),
            entry(6,"Central University of Andhra Pradesh, IT Incubation Centre Building, JNTU Campus, Chinmayanagar, Anantapuramu, Andhra Pradesh – 515002. (Central University)"),
            entry(7,"Centurion University of Technology and Management, Gidijala Junction, Anandapuram Mandal, Visakhapatnam – 531173, Andhra Pradesh. (Private University)"),
            entry(8,"Damodaram Sanjivayya National Law University, Plot No. 116, Sector 11 MVP Colony, Visakhapatnam – 530 017, Andhra Pradesh. (State University)"),
            entry(9,"Dr. Abdul Haq Urdu University, Kurnool – 518001, Andhra Pradesh. (State University)"),
            entry(10,"Dr. B.R. Ambedkar University, Etcherla, Dt. Srikakulam-532410, Andhra Pradesh. (State University)"),
            entry(11,"Dravidian University, Srinivasanam, -517 425, Chittoor District, Andhra Pradesh. (State University)"),
            entry(12,"Dr. Y.S.R. Horticultural University, PO Box No. 7, Venkataramannagudem, West Godavari District – 536 101, Andhra Pradesh. (State University)"),
            entry(13,"Dr. N.T.R. University of Health Sciences (Formerly Andhra Pradesh University of Health Sciences), Vijayawada-520 008, Andhra Pradesh. (State University)"),
            entry(14,"Gandhi Institute of Technology and Management (GITAM), Gandhi Nagar Campus, Rushikonda, Visakhapatman – 530 045, Andhra Pradesh.(Deemed University)"),
            entry(15,"Jawaharlal Nehru Technological University, Anantpur-515 002, Andhra Pradesh (State University)"),
            entry(16,"Jawaharlal Nehru Technological University, Pithapuram Road, Kakinada- 533003, East Godvari District, Andhra Pradesh.(State University)"),
            entry(17,"Koneru Lakshmaiah Education Foundation, Greenfields, Kunchanapalli Post, Vaddeswaram, Guntur District-522002, Andhra Pradesh. (Deemed University)"),
            entry(18,"KREA University, 5655, Central Expressway, Sri City-517646, Andhra Pradesh. (Private University)"),
            entry(19,"Krishna University, Andhra Jateeya Kalasala, Campus, Rajupeta, Machllipatanam – 521 001, Krishna District, Andhra Pradesh. (State University)"),
            entry(20,"Rajiv Gandhi University of Knowledge Technologies Andhra Pradesh, V.R. Mansions, Kunchanapalli, Guntur District, Andhra Pradesh. (State University)"),
            entry(21,"The National Sanskrit University, Tirupati-517 507, Chittoor District, Andhra Pradesh. (Central University)"),
            entry(22,"Rayalaseema University, Pasupula Village, Nandyal Road, Kurnool – 518 002, Andhra Pradesh. (State University)"),
            entry(23,"Saveetha Amaravati University, 03rd Floor, Vaishnavi Complex, Opp. Executive Club, Vijayawada – 520 008, Andhra Pradesh. (Private University)"),
            entry(24,"Sri Krishnadevaraya University, Anantapur-515 003, Andhra Pradesh. (State University)"),
            entry(25,"Sri Padmavati Mahila Vishwavidyalayam, Tirupati-517 502, Andhra Pradesh.(State University)"),
            entry(26,"Sri Sathya Sai Institute of Higher Learning, Prasanthinilayam, Anantapur-515134, Andhra Pradesh. (Deemed University)"),
            entry(27,"Sri Venkateswara University, Tirupati-517 502, Andhra Pradesh. (State University)"),
            entry(28,"Sri Venkateswara Vedic University, Alipiri-Chandragiri Bypass Road, Tirupati-517502, Andhra Pradesh. (State University)"),
            entry(29,"Sri Venkateswara Veterinary University, Dr. YSR Bhavan, Tirupati – 517 502,Andhra Pradesh. (State University)"),
            entry(30,"Sri Venkateswara Institute of Medical Sciences, Alipuri Road, Tirupati – 517507, Andhra Pradesh. (State University)"),
            entry(31,"SRM University, Neerukonda-Kuragallu Village, Mangalagiri Mandal, GunturDistrict-522502, Andhra Pradesh. (Private University)"),
            entry(32,"Vignan’s Foundation for Science, Technology and Research, Vadlamudi,Guntur District – 522213,, Andhra Pradesh. (Deemed University)"),
            entry(33,"Vikram Simhapuri University, Dargamitta, Nellore – 524 003, Andhra Pradesh.(State University)"),
            entry(34,"VIT-AP University, Amravati – 522237, Andhra Pradesh. (Private University)"),
            entry(35,"Yogi Vemana University, Vemanapuram, Kadapa – 516 003, Andhra Pradesh.(State University)"),
            entry(36,"Apex Professional University, Pasighat, District East Siang, Arunachal Pradesh – 791102. (Private University)"),
            entry(37,"Arunachal University of Studies, NH-52, Namsai, District Lohit – 792 103, Arunachal Pradesh. (Private University)"),
            entry(38,"Arunodaya University, E-Sector, Nirjuli, Itanagar, Distt. Papum Pare, Arunachal Pradesh-791109."),
            entry(39,"Himalayan University, 401, Takar Complex, Naharlagun, Itanagar, Distt – Papumpare – 791110, Arunachal Pradesh. (Private University)"),
            entry(40,"North East Frontier Technical University, Sibu-Puyi, Aalo (PO), West Siang (Distt.), Arunachal Pradesh –791001."),
            entry(41,"North Eastern Regional Institute of Science & Technology, Nirjuli, Itanagar- 791109, Arunachal Pradesh. (Deemed University)"),
            entry(42,"Rajiv Gandhi University, Rono Hills, PO Doimukh, Itanagar-791 112, Arunachal Pradesh. (Central University)"),
            entry(43,"The Global University, Hollongi, Itanagar, Arunachal Pradesh. (Private University)"),
            entry(44,"The Indira Gandhi Technological & Medical Sciences University, Ziro, Arunachal Pradesh. (Private University)"),
            entry(45,"Venkateshwara Open University, Itanagar, Arunachal Pradesh. (Private University)"),
            entry(46,"Assam Agricultural University, Jorhat- 785 013, Assam. (State University)"),
            entry(47,"Assam Don Bosco University, Azara, Guwahati-781017, Assam. (Private University)"),
            entry(48,"Assam Down Town University, Sankar Madhab Path, Gandhi Nagar, Panikhaiti, Guwahati – 781 036. (Private University)"),
            entry(49,"Assam University, PO Assam University, Silchar -788 011, Assam. (Central University)"),
            entry(50,"Assam Rajiv Gandhi University of Co-operative Management, 2nd Floor, Baruah Complex, Above SBI, Sivasagar-785040, Assam. (State University)"),
            entry(51,"Assam Science & Technology University, Kahilipara, Guwahati – 19, Assam.(State University)"),
            entry(52,"Assam Women’s University, Jorhat-785004, Assam. (State University) "),
            entry(53,"Bhattadev University, Bajali, Pathsala, Barpeta, Assam. (State University) "),
            entry(54,"Bodoland University, Debragaon, PO Rangalikhata, kokrajhar – 783 370, BTC, Assam. (State University)"),
            entry(55,"Central Institute of Technology (CIT), Balagaon, BTAD, Kokrajhar, Assam (Deemed University)"),
            entry(56,"Cotton College State University, Panbazar, Guwahati, Assam. (State University)"),
            entry(57,"Dibrugarh University, Dibrugarh-786 004, Assam. (State University) "),
            entry(58,"Gauhati University, Gopinath Bardoloi Nagar, Guwahati- 781 014, Assam. (State University)"),
            entry(59,"Krishnaguru Adhyatmik Vishwavidyalaya, Nasatra, Barpeta, Assam – 781307.(Private University)"),
            entry(60,"Krishna Kanta Handique State Open University, Housefed Complex, Last Gate, Dispur, Guwahati – 781 006, Assam. (State University)"),
            entry(61,"Kumar Bhaskar Varma Sanskrit & Ancient Studies University, Village – Namati, PO – Hati Namati, Dist. – Nalbari – 781 337, Assam. (State University)"),
            entry(62,"Madhabdev University, PO Dikrong – 184164, Narayanpur, Lakhimpur, Assam. (State University)"),
            entry(63,"Mahapurusha Srimanta Sankaradeva Viswavidyalaya, Srimanta Sankaradeva Sangha Complex, Haladhar Bhuyan Path, Kalongpar, Nagaon-782001, Assam.(Private University)"),
            entry(64,"Majuli university of Culture, Majuli, Assam. (State University) "),
            entry(65,"National Law University and Judicial Academy, NEJOTI Building, B.K. Kakati Road, Bholanath Mandir Path, Ulubari, Guwahati – 781 007, Assam. (StateUniversity)"),
            entry(66,"Rabindranath Tagore University, Hojai, Assam. (State University) "),
            entry(67,"Srimanta Sankaradeva University of Health Sciences, Narakasur Hilltop, Guwahati, Assam. (State University)"),
            entry(68,"Sri Sri Anirudhadeva Sports University, Chabua, Dibrugarh, Assam. (State University)"),
            entry(69,"Tezpur University, Napaam, Sonitpur, Assam- 784 028 (Central University) 1994"),
            entry(70,"The Assam Kaziranga University, Jorhat, Assam. (Private University) 11.04.2012"),
            entry(71,"The Assam Royal Global University, Betkuchi, Opp. Tirupati Balaji Temple, NH-37, Guwahati – 781035, Assam. (Private University)."),
            entry(72,"Al-Karim University, Near Katihar-Purnea Road, Sirsa, Karim Bagh, Katihar – 854106, Bihar. (Private University)"),
            entry(73,"Amity University, Rupaspur, Bailey Road, Patna – 801503, Bihar. (Private University)"),
            entry(74,"Aryabhatta knowledge University, 8, Off Polo Road, Patna – 800 001, Bihar  (State University)"),
            entry(75,"Babasaheb Bhimrao Ambedkar Bihar University, Muzaffarpur-842 001, Bihar.  (State University)"),
            entry(76,"Bhupendra Narayan Mandal University, Laloo Nagar, Madhepura –852 113, Bihar. (State University)"),
            entry(77,"Bihar Agricultural University, Sabour, Bhagalpur – 813210, Bihar. (State University)"),
            entry(78,"Bihar Animal Sciences University, Bihar Veterinary College Campus, Patna – 800014, Bihar. (State University)"),
            entry(79,"Central University of South Bihar, BIT Campus, PO-B.V. College, Patna- 800014. (Central University)."),
            entry(80,"Chanakya National Law University, Nyaya Nagar, Mithapur, Patna-800 001, Bihar. (State University)"),
            entry(81,"Dr. C.V. Raman University, Block – Bhagwanpur, NH-77 (Patna-Muzaffarpur Highway), District-Vaishali – 844114, Bihar. (Private University)"),
            entry(82,"Gopal Narayan Singh University, Jamuhar, Dist. - Rohtas – 821305, Bihar (Private University)"),
            entry(83,"Jai Prakash Vishwavidyalaya, Rahul Sankrityan Nagar, Chhapra –841 301, Bihar. (State University)"),
            entry(84,"Kameshwara Singh Darbhanga Sanskrit Vishwavidyalaya, Kameshwar Nagar, Darbhanga- 846008, Bihar. (State University)"),
            entry(85,"K.K. University, Berauti, Nepura, Biharsharif, Nalanda, Bihar – 803115. (Private University)"),
            entry(86,"Lalit Narayan Mithila University, Kameshwarnagar, Darbhanga- 846004, Bihar.(State University)"),
            entry(87,"Magadh University, Bodh Gaya.-824 234, Bihar. (State University) "),
            entry(88,"Mahatma Gandhi Central University, BIT Campus, PO-B.V. College, Patna 800014. (Central University)."),
            entry(89,"Mata Gujri University, Purabpalli Road, Kishanganj – 855107, Bihar. (Private University)"),
            entry(90,"Maulana Mazharul Haque Arabic & Persian University, 34, Ali Imam Path (Harding Road), Near Raj Bhawan, Patna-800 001, Bihar. (State University)"),
            entry(91,"Munger University, Munger, Bihar. (State University) "),
            entry(92,"Nalanda University, Rajgir, Dt. Nalanda, Bihar-803116. (Established underCentral Act)"),
            entry(93,"Nalanda Open University, Patna.-800 001 (State University) "),
            entry(94,"Nava Nalanda Mahavihara, Nalanda – 803 111. (Bihar) (Deemed University) "),
            entry(95,"Patliputra University, Kankarbagh Road, Near Rajendra Nagar Terminal, Patna– 800 020, Bihar. (State University)"),
            entry(96,"Patna University, Patna–800 005, Bihar. (State University) "),
            entry(97,"Purnea University, Purnea – 854301, Bihar. (State University) "),
            entry(98,"Rajendra Agricultural University, Pusa, Samastipur- 848 125, Bihar. (Central University)"),
            entry(99,"Sandip University, Village – Sijoul, Dist. – Madhubani – 847235, Bihar. (Private University)"),
            entry(100,"T.M. University, Bhagalpur- 812 007, Bihar. (State University) "),
            entry(101,"Veer Kunwar Singh University, Arrah- 802 301, Bihar. (State University) "),
            entry(102,"AAFT University of Media and Arts, Village – Maath, Tehsil – Tilda, dist. Raipur, Chhattisgarh. (Private University)"),
            entry(103,"Amity University, Village-Manth, Tehsil-Tilda, Distt-Raipur, Chhattisgarh. Private University)"),
            entry(104,"Atal Bihari Vajpai Vishwavidyalaya, Old High Court Building, Gandhi Chowk, Bilaspur - 495001, Chhattisgarh."),
            entry(105,"Ayush and Health Sciences University of Chhattisgarh, G.E. Road, Raipur-492001, Chhattisgarh. (State University)"),
            entry(106,"Bastar Vishwavidyalaya, Jagdalpur (Dharampura), Distt. – Bastar-494005, Chhattisgarh. (State University)"),
            entry(107,"Chhattisgarh Kamdhenu Vishwavidyalaya, Raipur College of Dairy Technology Campus, G.E. Road, Raipur, Chhattisgarh. (State University)"),
            entry(108,"Chhattisgarh Swami Vivekanand Technical University, North Park Avenue,Sector-8, Bhilai, Dt. Durg-490009, Chhattisgarh. (State University)."),
            entry(109,"Dr. C.V. Raman University, Kargi Road, Kota, Bilaspur-495113, Chhattisgarh (Private University)"),
            entry(110,"Durg Vishwavidyalaya, Government Vasudev Vaman Patankar Girls’ PGCollege Campus, Raipur Naka, Durg, Chhattisgarh. (State University)"),
            entry(111,"Guru Ghasidas Vishwavidyalaya, Koni, Bilaspur- 495 009, Chhattisgarh. (Converted State University to Central University) (Central University)"),
            entry(112,"Hidayatullah National Law University, Uparwara Post, Abhanpur, Raipur- 493661, Chhattisgarh. (State University)"),
            entry(113,"ICFAI University, NH-6, Raipur-Bhilai Road (Km Stone 20), Gram-Chorha, PO Kumhari, District Durg, Chhatttisgarh-490032. (Private University)"),
            entry(114,"International Institute of Information Technology, Plot No. 7, Sector 24, Near Purkhoti, Muktangan, Naya Raipur-493661, Chhattisgarh. (State University)"),
            entry(115,"ISBM University, Village – Nawapara (Kosmi) Block, tehsil – Chhura, Dist – Gariyaband – 493996, Chhattisgarh. (Private University)"),
            entry(116,"Indira Gandhi Krishi Vishwavidyalaya, Krishak Nagar, Raipur- 492 012, Chhattisgarh. (State University)"),
            entry(117,"Indira Kala Sangeet Vishwavidyalaya, Khairagarh, Dt. Rajnandgaon- 491 881, Chhattisgarh. (State University)"),
            entry(118,"ITM University, PH No. 137, Uparwara, Naya Raipur, Dt. Raipur – 493661, Chhattisgarh. (Private University)"),
            entry(119,"K.K. Modi University, Khasra No. 72,73,75,217 and 220, Village Mahmara, Jalbandha (Rasmada) Road, District Durg – 491001, Chhattisgarh. (Private University)"),
            entry(120,"Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya, Kathadih, Post Office Sunder Nagar, Raipur – 492 013, Chhattisgarh. (State University)."),
            entry(121,"Kalinga University, Raipur, Chhattisgarh. (Private University)"),
            entry(122,"Maharishi University of Management and Technology, Post: Mangla, Bilaspur –495 001, Chhattisgarh (Private University)."),
            entry(123,"MATS University, Arang Kharora Highway, Gram Panchayat: Gullu, Village:Gullu, Tehsil : Arang, District: Raipur-493441, Chhattisgarh (Private University)"),
            entry(124,"O.P. Jindal University, Knowledge Park, Gharghoda Road, Punjipathra,Raigarh-496001, Chhattisgarh (Private University)"),
            entry(125,"Pt. Ravishankar Shukla University, Raipur-492 010, Chhattisgarh. (StateUniversity)"),
            entry(126,"Pandit Sundarlal Sharma (Open) University, Village & PO Birkona, Koni-Birkona Road, Distt. Bilaspur-495009, Chhatisgarh. (State University)"),
            entry(127,"Sant Gahra Guru Vishwavidyalaya (Formerly Sarguja University),Daripara, Ambikapur, Sarguja – 497001, Chhattisgarh. (State University)"),
            entry(128,"Shaheed nandkumar Patel Vishwaidyalaya, Garhumaria, Odisha Road,raigarh, Chhattisgarh. (State University)"),
            entry(129,"Shri Rawatpura Sarkar University, Raipur, Chhattisgarh. (Private University)"),
            entry(130,"Shri Shankaracharya Professional University, Village – Junwani, Bhilai, distt.Durg, Chhattisgarh – 490020. (Private University)"),
            entry(131,"Goa University, Sub Post Office Goa University, Taleigao Plateau, Goa- 403 206. (State University)"),
            entry(132,"Ahmadabad University, AES Bungalow # 2, Near Commerce Six Roads, Navrangpura, Ahmedabad – 380 009, Gujarat. (Private University)"),
            entry(133,"Anand Agricultural Univerisity, Anand, Gujarat-388110. (State University)"),
            entry(134,"Anant National University, Sanskardham Campus, Bhopal-Ghuma-SanandRoad, Ahmedabad, Gujarat – 382115. (Private University)"),
            entry(135,"Atmiya University, Yogidham Gurukul, Kalawad Road, Rajkot – 360005,Gujarat. (Private University)"),
            entry(136,"AURO University of Hospitality and Management, Surat, Gujarat. (PrivateUniversity)"),
            entry(137,"Bhagwan Mahavir University, VIP Road, Vesu, Surat, Gujarat. (PrivateUniversity)"),
            entry(138,"Bhaikaka University, Karamsad, Gujarat. (Private University)"),
            entry(139,"Bhakta Kavi Narsinh Mehta University, C/o Government Polytechnic College, Bilkha Road, Khadiya, Junagadh – 362640, Gujarat. (State University)"),
            entry(140,"Birsa Munda Tribal University, Vocational Training Centre (VTC), Near RTO Office, Vavdi Road, Vavdi-Rajpipla, Dist – Narmada, Gujarat - 393145. (StateUniversity)"),
            entry(141,"Central University of Gujarat, Sector-30, Gandhinagar-382030, Gujarat(Central University)."),
            entry(142,"Centre for Environmental Planning and Technology University, University Road, Narvrangpura Ahemdabad-380 009 (Gujarat) (Private University)"),
            entry(143,"Charutar Vidya mandal (CVM) University, Opposite Shastri Maidan, Biside BVM College, Vallabh Vidyanagar, Dt. Anand, Gujarat – 388120. (Private University)"),
            entry(144,"Charotar University of Science & Technology, Akshar Dham, 12, Surya Valley,Bakrol Lambhavel Road, Bakrol, Anand – 388315, Gujarat. (Private University)"),
            entry(145,"Children’s University, Subhash Chandra Bose Shikshan Sankul, Sector-20,Gandhinagar - 382020, Gujarat. (State University)"),
            entry(146,"C.U. Shah University, Surendranagar-Ahmedabad State Highway, Near Kothariya Village, Wadhwan City – 363030, Dt. Surendranagar, Gujarat.(Private University)"),
            entry(147,"Dharmsinh Desai University, Post Box No. 35, College Road, Nadiad-387 001,Gujarat. (converted from Deemed University to State University)"),
            entry(148,"Dhirubhai Ambani Institute of Information and Communication Technology, Near Indroda Circle, Gandhinagar, Post Box No. 4, Gandhinagar-382 007, Gujarat. (Private University)"),
            entry(149,"Dr. Babasaheb Ambedkar Open University, R.C. Technical Institute Campus, Opp. Gujarat High Court, Sarkhej-Gandhinagar Highway, Sola, Ahmedabad –380 060, Gujarat. (State University)"),
            entry(150,"Ganpat University, Ganpat Vidyanagar, Mehsana, Goazaria Highway, Tal &District Mehsana – 384012, Gujarat. (Private University)"),
            entry(151,"G.L.S. University, Gujarat Law Society Campus, Opp. Law Garden, Ellisbridge,Ahmedabad-380006, Gujarat. (Private University)"),
            entry(152,"Gokul Global University, Gokul Educational Campus, Near GRSL, Sujanpur Patia, Sidhpur, Dist. Patan, Gujarat. (Private University)"),
            entry(153,"GSFC University, Vigyan Bhavan, PO Fertilizernagar – 391750, Dist.Vadodara, Gujarat. (Private University("),
            entry(154,"Gujarat Ayurveda University, Chanakya Bhavan, Jamnagar-360 118, Gujarat.(State University)"),
            entry(155,"Gujarat Biotechnology University, Gujarat State Biiotechnology Mission, Block 11, 9th Floor, Udyog Bhawan, Gandhinagar – 382011, Gujarat. (StateUniversity)"),
            entry(156,"Gujarat Maritime University, Gandhinagar, Gujarat. (Private University)"),
            entry(157,"Gujarat National Law University, Attalika Avenue, Knowledge Corridor, Koba,Gandhinagar, Gujarat – 382 007. (State University)"),
            entry(158,"Gujarat Technlogical University, Near Vishwakarma Government EngineeringCollege, Near Visat Three Roads, Visat-Gandhinagar Highway, Chandkheda,Ahmedabad-382414, Gujarat. (State University)"),
            entry(159,"Gujarat University, Post Box 4010, Navrangpura, Ahmedabad- 380 009,Gujarat. (State University)"),
            entry(160,"Gujarat University of Transplantation Sciences, IKDRC-ITS Premises, CivilHospital Campus, Asarwa, Ahmedabad – 380016, Gujarat. (State University)"),
            entry(161,"Gujarat Vidyapith, PO Navjivan, Ashram Road, Ahmedabad-380 014, Gujarat.(Deemed University)"),
            entry(162,"Gujarat Forensic Sciences University, Sector – 18/A, Near Police Bhavan, Gandhinagar – 382 007 Gujarat. (State University)"),
            entry(163,"Hemchandracharya North Gujarat University, University Road, Patan-384 265,Gujarat. (State University)"),
            entry(164,"Indian Institute of Public Health-Gandhinagar, Sardar Patel Institute of Economics and Social Research Campus, Drive-in-Road, Thaltej, Ahmedabad– 380054, Gujarat. (Private University)"),
            entry(165,"Indian Institute of Teacher Education, Government College Campus, Near Mahatma Mandir, G-4, Sector-15, Gandhinagar – 382 016, Gujarat. (State University)"),
            entry(166,"Indrashil University, Ratanpur, Dhandhuka, Ahmedabad – 382465, Gujarat.(Private University)"),
            entry(167,"Indus University, Indus Campus, Rancharda, Via-Thaltej, Ahmedabad –382115, Gujarat. (Private University)"),
            entry(168,"ITM (SLS) Baroda University, Paldi, Near Jarod, Vadodara-Halol Highway,Vadodara – 391510, Gujarat. (Private University)"),
            entry(169,"Institute of Infrastructure Technology Research and Management, Near Khokhra Circle, Maninagar (East), Ahmedabad-380026, Gujarat. (State University)"),
            entry(170,"Institute of Advanced Research, Institutional Area, Koba, Gandhinagar – 382007, Gujarat. (Private University)"),
            entry(171,"ITM-Vocational University, Plot 6512, Ajwa Nimeta Road, Ravaal Taluka, Waghodia, Vadodara, Gujarat. (Private University)"),
            entry(172,"J.G. University, Uvarsad, Distt. Gandhinagar – 380054, Gujarat. (Private University)"),
            entry(173,"Junagarh Agricultural University, University Bhavan, Motibaug, Junagarh – 362001, Gujarat. (State University)"),
            entry(174,"Kadi Sarva Vishwavidyalaya, Sector-15, Gandhinagar-382015, Gujarat. (Private University)"),
            entry(175,"Kamdhenu University, “Krushibhavan”, Sector 10 A, Block B, Podium Level, Gandhinagar – 382010, Gujarat. (State University)"),
            entry(176,"Karnavati University, 907/A, Uvarsad – 382422, Dt. Gandhinagar, Gujarat. (Private University)"),
            entry(177,"Krantiguru Shyamji Krishna Verma Kachchh University, Mundra Road, Bhuj, Kachchh-370001, Gujarat. (State University)"),
            entry(178,"Lakulish Yoga University, “Lotus View” Opp. Nirma University, S.G. Highway, Chharodi, Ahmedabad-382481, Gujarat. (Private University)"),
            entry(179,"Lok Jagruti Kendra University, FP No. 74, 100+113, TPS No. 86, (Sarkhej- Oakf-Fatewadi, Makrba), Dist. Ahmedabad, Gujarat. (Private University)"),
            entry(180,"Maharaja Krishnakumarsinji Bhavnagar University, S.V. Patel Campus, Gaurishanker Lake Road, Bhavnagar- 364 001, Gujarat. (State University)"),
            entry(181,"Maharaja Sayajirao University of Baroda, Opp Foods & Drugs Laboratory, Fatehganj, Vadodara-390 002, Gujarat. (State University)"),
            entry(182,"Marwadi University, Rajkot-Morbi Highway, Rajkot – 360003, Gujarat. (Private University)"),
            entry(183,"National Rail and Transportation Institute (NRTI), NAIR Campus, Lalbaug, Vadodara, Gujarat. (Deemed University)"),
            entry(184,"Navsari Agricultural University, Navsari-396450, Gujarat. (State University)"),
            entry(185,"Nirma University, Sarkhej-Gandhinagar Highway, Village-Chharodi, Ahmedabad-382481, Gujarat (Private University)."),
            entry(186,"Navrachana University, Vasna-Bhayli Road, Vadodara – 391410, Gujarat(Private University)"),
            entry(187,"Pandit Deendayal Petroleum University, Knowledge Corridor, Raisan, Dist.Gandhinagar – 382007, Gujarat.(Private University)"),
            entry(188,"Parul University, PO Limda, Tal – Waghodia, Dist. Vadodara-391760, Gujarat.(Private University)"),
            entry(189,"Plastindia International University, Dungra, GIDC, VAPI, Dist. Valsad –396195, Gujarat. (Private University)"),
            entry(190,"P.P. Savani University, NH-8, GETCO, Near Biltech, Village – Dhamdod,Kosamba, Ta – Mangrol, Dist – Surat – 394125, Gujarat. (Private University)"),
            entry(191,"R.K. University, Rajkot-Bhavnagar Highway, Kasturbadham, Rajkot, Gujarat.(Private University)"),
            entry(192,"Rai University, Ahmedabad, Gujarat. (Private University)"),
            entry(193,"Sabarmati University, Ahmadabad. (Private University)"),
            entry(194,"Sankalchand Patel University, Sankalchand Patel Vidyadham, Visanagar-384315, Gujarat. (Private University)"),
            entry(195,"Sardar Krushinagar Dantiwada Agricultural University, Sardar Krushinagar –385506, Dist. – Banaskantha, Gujarat. (State University)"),
            entry(196,"Sardar Patel University, Vallabh Vidyanagar, Dt. Anand – 388 120, Gujarat.(State University)"),
            entry(197,"Saurashtra University, University Road, Rajkot- 360 005, Gujarat. (State University)"),
            entry(198,"Shree Somnath Sanskrit University, Somnath-Veraval, District Junagarh-362265, Gujarat. (State University)"),
            entry(199,"Shri Govind Guru University, Government Polytechnic Campus, Gadukpur,Godhra, Dist. Panchmahals-389001, Gujarat. (State University)"),
            entry(200,"Shreyarth University, C/o Gujarat Samachar Bhavan, Khanpur, Ahmedabad,Gujarat. (Private University)"),
            entry(201,"Silver Oak University, S.G. Highway, Gota, Ahmedabad, Gujarat. (Private University)"),
            entry(202,"Sumandeep Vidyapeeth, Village Piparia, Taluka Waghodia, District Vadodara(Deemed University)"),
            entry(203,"Swarnim Gujarat Sports University, PTC Building, Near Inquiry Office, Sector-19, Punit Van Road, Near – Suvidha Kendra, PTC Building Campus,Gandhinagar – 382 019, Gujarat. (State University)"),
            entry(204,"Swarnim Startup & Innovation University, Bhoyan Rathod Rathod, Opp.IFFCO, Adalaj-Sertha Road, Gandhinagar – 382420, Gujarat. (PrivateUniversity)"),
            entry(205,"Team Lease Skills University, Tarsali-Vadodara Road, Tarsali Bypass,Vadodara – 390009, Gujarat. (Private University)"),
            entry(206,"UKA Tarsadia University, Maliba Campus, Gopal vidyanagar, Baroli-Mahuva Road, Tal. Mahuva, Dist. Surat-394350, Gujarat. (Private University)"),
            entry(207,"Veer Narmad South Gujarat University, University Campus, Udhna-Magdalla Road, Surat-395007, Gujarat. (State University)")
    );
}
